baseURL = 'https://pooria.online/'
languageCode = 'en-us'
title = "pourya:/var/log"
theme = 'pourya'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Homepage"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

homeIntroTitle = "About Me"
homeIntroContent = """
I'm [Pourya](https://en.wikipedia.org/wiki/Pouria) Mokhtari, a computer engineer specializing in distrubted systems, applied machine learning and cryptography. I'm currently a research assistant at [Information, Network and Learning Labs](https://inl-lab.net) in Sharif University of Technology.

My research focuses on developing machine-learning models for detecting anomalies in the context of Intrusion Detection Systems.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "email"
url = "mailto:contact@pouryamokhtari.com"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/pooriamokhtari/"

[[params.social]]
name = "github"
url = "https://github.com/p0m0h3"

# Main menu pages
#[[params.menu]]
#name = "home"
#url = "/"
#
#[[params.menu]]
#name = "posts"
#url = "/posts"
#
#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
